### ISSUE TITLE
McCree answers messages that aren't questions

### ISSUE THREAD

**Issue by tevert** [shankera/mccree-bot#1]
Example: "
When it comes to hosting microservices like chat bots, heroku is actually just a good option" will trigger McCree.

Suggested fix: also check for a question mark in the message.

**Comment by shankera** [comment]
we don't use punctuation enough for this to be a valid fix

Instead it'll check for 'when will', 'when are', 'when is', 'when did' etc. I'll implement this fix later this evening probably
